theme: jekyll-theme-tactile

defaults:
  - scope:
      path: "files/1.méthodes"
    values:
      methodes: true
  - scope:
      path: "files/2.modèles"
    values:
      modeles: true

  - scope:
      path: "files/3.cas-d-usages"
    values:
      casdusages: true

